language: csharp
mono: none
dotnet: 3.1
install:
  - dotnet restore src/GlobalX.ChatBots.WebexTeams.sln
  - dotnet build src/GlobalX.ChatBots.WebexTeams/GlobalX.ChatBots.WebexTeams.csproj
jobs:
  include:
    - stage: test
      script: dotnet test src/GlobalX.ChatBots.WebexTeams.Tests/GlobalX.ChatBots.WebexTeams.Tests.csproj
    - stage: deploy
      skip_cleanup: true
      provider: script
      script: chmod +x ./deploy.sh && ./deploy.sh $NUGET_API_KEY
      if: branch = master
    - stage: cover
      provider: script
      script: chmod +x ./cover.sh && ./cover.sh
